name: Autodocs Documentation Generator

on:
  workflow_dispatch:
    inputs:
      jsdoc:
        description: 'Generate code comments (T/F)'
        required: true
        default: 'T'
        type: choice
        options: [T, F]
      readme:
        description: 'Generate README documentation (T/F)'
        required: true
        default: 'T'
        type: choice
        options: [T, F]
      pull_number:
        description: 'Pull Request Number (if not provided, scans root_directory) - PR must be merged to develop branch. DONT provide if `README documentation` is T from above'
        required: false
        type: string
      root_directory:
        description: 'Only scans files in this directory (relative to repository root, e.g., packages/core/src)'
        required: true
        default: 'src'
        type: string
      excluded_directories:
        description: 'Directories to exclude from scanning (comma-separated, relative to root_directory)'
        required: true
        default: 'node_modules,dist,test'
        type: string
      reviewers:
        description: 'Pull Request Reviewers (Must be collaborator on the repository) comma-separated GitHub usernames'
        required: true
        default: ''
        type: string
      branch:
        description: 'Target branch for PR (defaults to main)'
        required: false
        default: 'main'
        type: string

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install Autodoc
        run: |
          pwd
          npm install -g @nydiokar/autodoc

      - name: Run documentation generator
        run: autodoc .
        env:
          INPUT_PULL_NUMBER: ${{ github.event.inputs.pull_number }}
          INPUT_ROOT_DIRECTORY: ${{ github.event.inputs.root_directory }}
          INPUT_EXCLUDED_DIRECTORIES: ${{ github.event.inputs.excluded_directories }}
          INPUT_REVIEWERS: ${{ github.event.inputs.reviewers }}
          INPUT_BRANCH: ${{ github.event.inputs.branch }}
          INPUT_JSDOC: ${{ github.event.inputs.jsdoc }}
          INPUT_README: ${{ github.event.inputs.readme }} 